theme: jekyll-theme-minimal
title: TEP - Thames Catchment Community Eels Project
description: Workshop materials for the Thames Catchment Community Eels Project
logo: https://raw.githubusercontent.com/ThamesEstuaryPartnership/thameseels/main/Eel%20Project_Final%20Logo%20png.png
